### ISSUE TITLE
サーバー構成どうする

### ISSUE THREAD

**Issue by manzyun** [ZenryokuService/LiveHouseMap#3]
SPAを検討しているので、サーバーはJSON返せればいいかなあ程度だったりもする。

であれば、格安のWordPressくらいしか乗っからないサーバーでCGIでやるかという話。

# 懸念点

* アクセスが想定以上に増えたときの対処
* ユーザー（お店ユーザー）どうする？ -> 今WordPressの個人ページで管理している。

Webアプリとしてしっかり作ったほうが良い気がするのだがなあ……。

**Comment by manzyun** [comment]
無闇に複数のフレームワークを結合する様な作りだと、それぞれのプログラムの脆弱性チェックなどが非常に面倒。

かといってサーバー管理するのも面倒なのだが。

---

過去にWordPressで「地域密着婚活パーティー企画サイト」の開発に参加した経験からすると、非常に悪手。WordPressはあくまでCMSなので、それ以上の事をやるのは危ない。

提供する機能を整理した上で、適当なフレームワークやライブラリを使い、新たにシステムを組んだほうがいい気がする。

---

AndroidやiOSのネイティブアプリを開発する話も入ってきたので、本格的にフルスクラッチで書いたほうがいい気がする。

**Comment by ZenryokuService** [comment]
シンプルにphp + ajax(js)で作る予定。
cgiなどはjavaとかを使って実装する場合の話(笑)
次の段階でユーザー(店舗オーナーなど)の広告情報を表示できるようにする予定だが、それは別にする。
接続に関しては、電文などを使用して外部サーバを使う予定。
まだ先だから、今は考えない。
